name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build For Linux
      run: go build -o release/linux/prosql-agent

    - name: Build For Mac
      run: GOOS=darwin GOARCH=amd64 go build -o release/mac/prosql-agent
